### ISSUE TITLE
Add flag to disable p2p

### ISSUE THREAD

**Issue by lukehmcc** [s5-dev/S5#8]
Some users may wish to simply use an S5 node as a way to do multi-backend remote storage. Having a flag to remove p2p would be useful for this usecase.

**Comment by parajbs** [comment]
Hello @lukehmcc,

I don't think it's necessary to remove or switch off p2p, you can empty the "p2p.peers" area in config.toml with the initial part.

[p2p.peers]
initial = []

and you can still create these entries so that the p2p only runs on the localhost:

[p2p.self.tcp]
ip="127.0.0.1"
port = 4444
 
If you are unsure then you can block "127.0.0.1:4444" with a firewall for everything.

**Comment by redsolver** [comment]
If you don't specify `p2p.self.tcp`, it doesn't even run a local p2p server

**Comment by redsolver** [comment]
The correct solution is to leave the `peers` array and other `p2p` config options empty, that should completely disable p2p functionality.
